global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets:
        - 10.0.0.21:9002
        - 10.0.0.22:9002
        - 10.0.0.23:9002
        - 10.0.0.20:9002

  - job_name: "internal"
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:9090 # Prometheus metrics
